apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csos-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bsos-cr
subjects:
- kind: ServiceAccount
  name: bsos-sa
  namespace: default
